//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphanemiz.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cezalar
    {
        public int CezaID { get; set; }
        public int EmanetID { get; set; }
        public decimal BirimCeza { get; set; }
        public int GGunSayisi { get; set; }
        public decimal ToplamCeza { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Emanetler Emanetler { get; set; }
    }
}
