//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphanemiz.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emanetler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emanetler()
        {
            this.Cezalar = new HashSet<Cezalar>();
        }
    
        public int EmanetID { get; set; }
        public int KullaniciID { get; set; }
        public int KitapID { get; set; }
        public System.DateTime KVerilisTarihi { get; set; }
        public System.DateTime KIEdilecekTarih { get; set; }
        public Nullable<System.DateTime> KIEdildigiTarih { get; set; }
        public decimal BirimCeza { get; set; }
        public Nullable<int> GGunSayisi { get; set; }
        public Nullable<decimal> ToplamCeza { get; set; }
        public bool Silindi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cezalar> Cezalar { get; set; }
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
