//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphanemiz.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.Emanetler = new HashSet<Emanetler>();
        }
    
        public int KitapID { get; set; }
        public string Barkod { get; set; }
        public string KitapAd { get; set; }
        public int YayineviID { get; set; }
        public int YazarID { get; set; }
        public int KategoriID { get; set; }
        public int Adet { get; set; }
        public string Durum { get; set; }
        public System.DateTime EkTarihi { get; set; }
        public bool Silindi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emanetler> Emanetler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Yayinevleri Yayinevleri { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
